# IMPORTANT: Please build from the root monorepo directory!

# Use rust image as build image.
FROM rust:1.43 AS build
WORKDIR /usr/src/

# Copy all files to working directory.
COPY lyrical-cli/Cargo.toml lyrical-cli/Cargo.lock ./lyrical-cli/
COPY lyrical-cli/src ./lyrical-cli/src/
COPY liblyrical ./liblyrical/

# Debug info.
RUN cargo --version
RUN rustc --version
RUN ls -Rla

# Move into working dir.
WORKDIR /usr/src/lyrical-cli

# Build the binary.
RUN cargo build --release

# Run binary on scratch image.
FROM alpine
COPY --from=build /usr/src/lyrical-cli/target/release/lyrical-cli ./
RUN ls
CMD ["./lyrical-cli"]